### ISSUE TITLE
benchmark跑分記錄(記錄到wiki中)

### ISSUE THREAD

**Issue by sashimi-yzh** [NJUCS-ComputerSystemLab-2017/old-loongson#3]

**Comment by userhr** [comment]
见群中照片

**Comment by sashimi-yzh** [comment]
把照片貼上來啊

**Comment by Paraoia** [comment]
那个照片时钟不准确，明天重新跑一次再上传。

**Comment by sashimi-yzh** [comment]
這個issue長期開着, 每當有改進就記錄一下得分.

**Comment by sashimi-yzh** [comment]
把信息輸出到uart, 直接粘貼過來, 就可以不用貼照片了.

**Comment by Paraoia** [comment]
No1、初始跑分(9 Passed, 1 Failed)

[qsort] Quick sort: * Passed.
    min time: 448784K cycles in 440979 ms [6]
[queen] Queen placement: * Passed.
    min time: 401280K cycles in 37274 ms [14]
[bf] Brainf**k interpreter: * Passed.
    min time: 2980164K cycles in 277121 ms [6]
[fib] Fibonacci number: * Passed.
    min time: -..*,)*K cycles in 497896 ms [5]
[sieve] Eratosthenes sieve: * Passed.
    min time: 583079K cycles in 453679 ms [9]
[15pz] A* 15-puzzle search: * Passed.
    min time: 775950K cycles in 72099 ms [8]
[dinic] Dinic's maxflow algorithm: * Passed.
    min time: 1220768K cycles in 113456 ms [13]
[lzip] Lzip compression: X Failed.
    min time: -**'-0)K cycles in 58134 ms [14]
[md5] MD5 digest: * Passed.
    min time: /.+,'+'K cycles in 282734 ms [7]
[ssort] Suffix sort: * Passed.
    min time: 705319K cycles in 65550 ms [7]
==================================================
MicroBench FAIL        8 Marks
				   vs. 100000 Marks (i7-6700 @ 3.40GHz)
Panic

**Comment by Paraoia** [comment]
No1、初始跑分(9 Passed, 1 Failed)

`[qsort] Quick sort: * Passed.
    min time: 448784K cycles in 440979 ms [6]
[queen] Queen placement: * Passed.
    min time: 401280K cycles in 37274 ms [14]
[bf] Brainf**k interpreter: * Passed.
    min time: 2980164K cycles in 277121 ms [6]
[fib] Fibonacci number: * Passed.
    min time: -..*,)*K cycles in 497896 ms [5]
[sieve] Eratosthenes sieve: * Passed.
    min time: 583079K cycles in 453679 ms [9]
[15pz] A* 15-puzzle search: * Passed.
    min time: 775950K cycles in 72099 ms [8]
[dinic] Dinic's maxflow algorithm: * Passed.
    min time: 1220768K cycles in 113456 ms [13]
[lzip] Lzip compression: X Failed.
    min time: -**'-0)K cycles in 58134 ms [14]
[md5] MD5 digest: * Passed.
    min time: /.+,'+'K cycles in 282734 ms [7]
[ssort] Suffix sort: * Passed.
	min time: 705319K cycles in 65550 ms [7]
==================================================
MicroBench FAIL        8 Marks
				   vs. 100000 Marks (i7-6700 @ 3.40GHz)
Panic
`

**Comment by Paraoia** [comment]
No1、初始跑分(9 Passed, 1 Failed)
```
[qsort] Quick sort: * Passed.
    min time: 448784K cycles in 440979 ms [6]
[queen] Queen placement: * Passed.
    min time: 401280K cycles in 37274 ms [14]
[bf] Brainf**k interpreter: * Passed.
    min time: 2980164K cycles in 277121 ms [6]
[fib] Fibonacci number: * Passed.
    min time: -..*,)*K cycles in 497896 ms [5]
[sieve] Eratosthenes sieve: * Passed.
    min time: 583079K cycles in 453679 ms [9]
[15pz] A* 15-puzzle search: * Passed.
    min time: 775950K cycles in 72099 ms [8]
[dinic] Dinic's maxflow algorithm: * Passed.
    min time: 1220768K cycles in 113456 ms [13]
[lzip] Lzip compression: X Failed.
    min time: -**'-0)K cycles in 58134 ms [14]
[md5] MD5 digest: * Passed.
    min time: /.+,'+'K cycles in 282734 ms [7]
[ssort] Suffix sort: * Passed.
	min time: 705319K cycles in 65550 ms [7]
==================================================
MicroBench FAIL        8 Marks
                   vs. 100000 Marks (i7-6700 @ 3.40GHz)
Panic

```

**Comment by sashimi-yzh** [comment]
註明一下配置, 例如時鐘頻率, 是否轉發, 什麼樣的分支預測, 是否有cache, 用什麼替換算法 等各種微結構特性, 到時候我們就是要比較不同的微結構特性能帶來多少的性能提升

**Comment by jiangyy** [comment]
我觉得可以在项目里开个.md文档记录这个？

**Comment by sashimi-yzh** [comment]
可以啊, 可能還要想一下怎麼對比比較方便人來看

**Comment by jiangyy** [comment]
@sashimi-yzh 以yaml形式记录在wiki上怎么样？

自动生成历史记录：
https://njucs-computersystemlab-2017.github.io/wiki/history/index.html

源文件：
https://github.com/NJUCS-ComputerSystemLab-2017/wiki/blob/master/src/history/1.yaml

记录规范可以我们来定。

**Comment by sashimi-yzh** [comment]
可以啊, IPC也可以算一下

**Comment by jiangyy** [comment]
他们现在没有performance counter，所以暂时还没法统计。

现在暂时也不知道指令的数量（编译组的工具每秒只能执行几千条指令，跑不完）。

有这两个任意一个就能推算了。到时候加上就行。

**Comment by sashimi-yzh** [comment]
噢忘了perf cnt, 讓NPC那邊弄幾個吧, 可以統計各種東西

**Comment by Paraoia** [comment]
No2、频率提升(9 Passed, 1 Failed)
```
[qsort] Quick sort: * Passed.
  min time: 960667K cycles in 103024 ms [27]
[queen] Queen placement: * Passed.
  min time: 495258K cycles in 9704 ms [56]
[bf] Brainf**k interpreter: * Passed.
  min time: 4293785061K cycles in 61021 ms [28]
[fib] Fibonacci number: * Passed.
  min time: 2582107K cycles in 134772 ms [21]
[sieve] Eratosthenes sieve: * Passed.
  min time: 1071898K cycles in 105217 ms [39]
[15pz] A* 15-puzzle search: * Passed.
  min time: 4291620897K cycles in 18589 ms [31]
[dinic] Dinic's maxflow algorithm: * Passed.
  min time: 1597423K cycles in 31308 ms [47]
[lzip] Lzip compression: X Failed.
  min time: 767803K cycles in 15048 ms [57]
[md5] MD5 digest: * Passed.
  min time: 4293717849K cycles in 59706 ms [33]
[ssort] Suffix sort: * Passed.
  min time: 841529K cycles in 16494 ms [30]
==================================================
MicroBench FAIL        36 Marks
                   vs. 100000 Marks (i7-6700 @ 3.40GHz)
Panic

```
系统配置说明

```
CPU配置：
描述：                   MIPS32单发射流水线CPU
流水线段数：             5 @ IF/ID/EX/MEM/WB
时钟频率：               50MHz
是否存在转发逻辑：	是
分支预测逻辑：		无
取指时延：	        >= 2 cycle
load/store时延：		>= 2 cycle
乘法时延：		2 cycle
除法时延：		66 cycle
中断异常支持：	        时钟中断
精确异常：               不完全(Lo、Hi造成)
MMU：		        不支持
====================================
IO：
外设种类：	        uart、ddr、vga
总线类型：		AXI
Cache:			无
Cache替换算法：		无
```

**Comment by jiangyy** [comment]
@Paraoia 记录到wiki项目里的yaml文件里，格式参考src/history/1.yaml。
@sashimi-yzh 这个issue要不要close？

**Comment by sashimi-yzh** [comment]
那就close吧, 以後統一記錄到wiki裡面.
